# # Use the appropriate linker
# [target.x86_64-unknown-linux-musl]
# linker = "musl-gcc"

# For building branelet and stuff for M1 macs on Linux:
[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
